### PR TITLE
Feature/sl sh token colors

### PR DESCRIPTION
**Pull request by gpwclark**

### CODE REVIEW

**Comment by gpwclark** [comment]
can't push to master so I just put my contrib changes in here

**Comment by gpwclark** [comment]
scratch that... I had to hit a button in an email, i think i can push  now

**Comment by gpwclark** [comment]
ugh. ok. for convenience, accept the README.md, then i'll merge, then i'll update the readme to include the new color stuff then this PR will be ready to go.

**Comment by gpwclark** [comment]
ok, i think this is ready to go.

**Comment by sstanfield** [comment]
Github says you have a conflict with contrib/gpwclark/slshrc that needs resolving...

**Pull request merged**
